# Generated by Django 2.2.3 on 2019-08-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shopname',
        ),
    ]
